version: '3.8'

services:
  api:
    build: .
    container_name: task-api
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/taskdb
    env_file:
      - .env
    depends_on:
      - mongo
    command: npm start  # Démarre TypeScript avec Node.js

  mongo:
    image: mongo:latest
    container_name: mongo
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

volumes:
  mongo-data:
