version: '3.8'

services:
  api:
    build: .
    container_name: api
    ports:
      - "3000:3000"
    environment:
      MONGO_URI: mongodb://mongo:27017/cesieatsdb
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: cesieats_db
    env_file:
      - .env
    depends_on:
      mongo:
        condition: service_healthy
      mysql:
        condition: service_healthy
    command: npm start

  mongo:
    image: mongo:latest
    container_name: mongo
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 5s

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cesieats_db
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234
    volumes:
      - sql-data:/var/lib/mysql
      - ./database/architecture-datas.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5

volumes:
  mongo-data:
  sql-data:
